version: '3.9'

services:
  mongoDb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root-java
        MONGO_INITDB_ROOT_PASSWORD: password-java
        MONGO_INITDB_DATABASE: java
